name: Update README Stats

on:
  schedule:
    - cron: "0 * * * *" # updates hourly
  workflow_dispatch: # manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.PAT_1 }}
