name: Update README Stats

on:
  schedule:
    - cron: "0 * * * *" # updates hourly
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Generate GitHub Stats
      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.PAT_1 }}
          username: lu-nch
          show_icons: true
          hide_border: true
          theme: dark
          bg_color: 0d0b1f
          icon_color: ef4444
          ring_color: b91c1c
          title_color: dc2626
          text_color: ffffff
          count_private: true
          output: stats/github-stats.svg

      # Generate GitHub Streak
      - name: Generate GitHub Streak
        uses: ludeeus/streak-stats@v1
        with:
          user: lu-nch
          theme: dark
          background: 0D0B1F
          ring: dc2626
          fire: ef4444
          currStreakLabel: dc2626
          sideNums: ef4444
          sideLabels: ffffff
          dates: 9ca3af
          output: stats/github-streak.svg

      # Generate Top Languages
      - name: Generate Top Languages
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.PAT_1 }}
          username: lu-nch
          layout: compact
          hide_border: true
          theme: dark
          bg_color: 0d0b1f
          title_color: dc2626
          text_color: ffffff
          count_private: true
          output: stats/top-langs.svg

      # Generate Activity Graph
      - name: Generate Activity Graph
        uses: platane/snk@v1
        with:
          username: lu-nch
          theme: dark
          line: dc2626
          point: b91c1c
          area: true
          area_color: 7f1d1d
          background: 0d0b1f
          hide_border: true
          output: stats/activity-graph.svg

      # Commit the stats images
      - name: Commit and push stats
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add stats/
          git commit -m "Update GitHub stats"
          git push
