name: Update README Stats

on:
  schedule:
    - cron: "0 * * * *" # updates hourly
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Generate GitHub Stats with private repos
      - name: Generate GitHub Stats
        run: |
          mkdir -p stats
          curl -o stats/github-stats.svg "https://github-readme-stats.vercel.app/api?username=lu-nch&show_icons=true&hide_title=true&hide_border=true&theme=dark&bg_color=0d0b1f&icon_color=ef4444&ring_color=b91c1c&text_color=ffffff&title_color=dc2626&count_private=true&token=${{ secrets.PAT_1 }}"

      # Generate Top Languages
      - name: Generate Top Languages
        run: |
          curl -o stats/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=lu-nch&layout=compact&hide_border=true&theme=dark&bg_color=0d0b1f&title_color=dc2626&text_color=ffffff&count_private=true&token=${{ secrets.PAT_1 }}"

      # Generate GitHub Streak
      - name: Generate GitHub Streak
        run: |
          curl -o stats/github-streak.svg "https://streak-stats.demolab.com?user=lu-nch&theme=dark&hide_border=true&background=0D0B1F&ring=dc2626&fire=ef4444&currStreakLabel=dc2626&sideNums=ef4444&sideLabels=ffffff&dates=9ca3af"

      # Generate Activity Graph
      - name: Generate Activity Graph
        run: |
          curl -o stats/activity-graph.svg "https://github-readme-activity-graph.vercel.app/graph?username=lu-nch&bg_color=0d0b1f&color=ef4444&line=dc2626&point=b91c1c&area=true&area_color=7f1d1d&hide_border=true"

      # Commit and push changes
      - name: Commit stats
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add stats/
          git commit -m "Update GitHub stats" || echo "No changes to commit"
          git push
